//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.mu6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    //  *** Start programmer edit section *** (Using statements)

    //  *** End programmer edit section *** (Using statements)


    /// <summary>
    /// K4.
    /// </summary>
    //  *** Start programmer edit section *** (K4 CustomAttributes)

    //  *** End programmer edit section *** (K4 CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("K4E", new string[0])]
    [View("K4L", new string[0])]
    public class K4 : ICSSoft.STORMNET.DataObject
    {
        
        //  *** Start programmer edit section *** (K4 CustomMembers)

        //  *** End programmer edit section *** (K4 CustomMembers)

        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "K4E" view.
            /// </summary>
            public static ICSSoft.STORMNET.View K4E
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("K4E", typeof(IIS.mu6.K4));
                }
            }
            
            /// <summary>
            /// "K4L" view.
            /// </summary>
            public static ICSSoft.STORMNET.View K4L
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("K4L", typeof(IIS.mu6.K4));
                }
            }
        }
    }
}
